import type { Metadata } from 'next';

import './globals.css';

import { env } from '@/env';
import { inter } from '@/lib/fonts';
import { cn } from '@/lib/utils';

import { Providers } from './providers';

export const metadata: Metadata = {
  metadataBase: new URL(env.NEXT_PUBLIC_APP_URL),
  title: {
    default: 'Next.js Template',
    template: '%s',
  },
  description: 'Generated by create next app',
  applicationName: 'Vigil',
  openGraph: {
    siteName: 'Vigil',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
  },
  appleWebApp: {
    title: 'Vigil',
  },
};

export default function RootLayout({ children }: Readonly<LayoutProps<'/'>>) {
  return (
    <html
      lang="en"
      className={cn('antialiased', 'font-sans', inter.variable)}
      suppressHydrationWarning
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
